# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: kexec-tools.spec

# add or remove files that should be synced
files_to_sync:
    - kexec-tools.spec
    - .packit.yaml

# name in upstream package repository or registry (e.g. in PyPI)
upstream_package_name: kexec-tools
# downstream (Fedora) RPM package name
downstream_package_name: kexec-tools

upstream_tag_template: v{version}
